# MLflow configuration
MLFLOW_TRACKING_URI: "http://localhost:5001"
MLFLOW_REGISTRY_URI: "http://localhost:5001"
EXPERIMENT: "news-recommendation-dev"
MODEL_NAME: "news-recommender-dev"

# API configuration
API_HOST: "0.0.0.0"
API_PORT: 8000
MODEL_ALIAS: "champion"

# Storage configuration
USE_S3: false
S3_BUCKET: "fiap-mleng-datathon-data-grupo57"
DATA_PATH: "data/"

# Features configuration
COLD_START_THRESHOLD: 5
SAMPLE_RATE: 0.10
SCALING_RANGE: 100
NEWS_DIRECTORY: "challenge-webmedia-e-globo-2023/itens/itens"
USERS_DIRECTORY: "challenge-webmedia-e-globo-2023/files/treino"

# Model hyperparameters
MODEL_PARAMS:
  threshold: 0.5
  top_k: 5
